# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            My untold journal
tagline:          'Exploring the past and future of game design.'
description:      'A space where I explore game design ideas and showcase my personal creations.'
url:              https://110477.xyz/
baseurl:          /

author:
  name:           'Jose Miguel Guerrero'
  url:            https://t.me/jmiguelguerrero

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/jmiguelguerrero/jmiguelguerrero.github.io
