# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            My untold journal
tagline:          'A Jekyll theme'
description:      'Registro en el que pretendo plasmar mis ideas sobre diseño de juegos y mis propias creaciones.'
url:              http://jmiguelguerrero.site
baseurl:          /

author:
  name:           'Jose Miguel Guerrero'
  url:            https://t.me/jmiguelguerrero

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jmiguelguerrero/jmiguelguerrero.github.io
